language: cpp

matrix:
  include:

    - os: linux
      compiler:
        - gcc

      install:
        - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
            
          packages:
            - cmake
            - cmake-data
            - g++-4.9
            - gcc-4.9

      env: COMPILER=g++-4.9
      
      script:
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

      after_success:
        - cd ../../demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make
        - cd ../../VAD/
        - mkdir build
        - cd build
        - cmake .. && make

    - os: osx
      osx_image: xcode7.3

      script:
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

      after_success:
        - cd ../../demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make
        - cd ../../VAD/
        - mkdir build
        - cd build
        - cmake .. && make
