language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc4.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - cmake
            - cmake-data
      script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        - sudo apt-get update -qq
        - sudo apt-get install g++-4.9
        - sudo update-alternatives --remove-all gcc
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
        - sudo update-alternatives --config gcc
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

      after_success:
        - cd ../../demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make
        - cd ../../VAD/
        - mkdir build
        - cd build
        - cmake .. && make

    - os: osx
      osx_image: xcode7.3
      script:
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

      after_success:
        - cd ../../demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make
        - cd ../../VAD/
        - mkdir build
        - cd build
        - cmake .. && make
