language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - cmake
            - cmake-data
      script:
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

      #after_success:
      #  - cd tests

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
          packages:
            - cmake
            - cmake-data
      script:
        - cd demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make

    - os: osx
      osx_image: xcode7.3
      script:
        - cd src
        - mkdir build
        - cd build
        - cmake .. && make

    - os: osx
      osx_image: xcode7.3
      script:
        - cd demo/ApproxAligner
        - mkdir build
        - cd build
        - cmake .. && make
